### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [razorpay/razorpay-ios-sample-app#11]
Trying to run sample app on Xcode 9.4 and I am getting following error

`dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/chandra/Library/Developer/CoreSimulator/Devices/88D3F27C-F401-455B-AE6E-EC11513A2C1E/data/Containers/Bundle/Application/336714B5-4C15-4C23-8376-5CF5EEDF6A5B/Razorpay Demonstration.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found
Message from debugger: Terminated due to signal 6`

**Comment by kaumudpa** [comment]
Same Problem here, This needs urgent attention.

**Comment by Mayur-Wadpalliwar** [comment]
@kaumudpa @ChandraPrakashJangid Please refer FAQ 3 here: https://razorpay.com/docs/ios/faq/

Also, please have a look at our integration videos available here: https://razorpay.com/docs/ios/integration-videos/

**Comment by kaumudpa** [comment]
@Mayur-Wadpalliwar The solutions Mentioned in the FAQ 3 are not working.

**Comment by Mayur-Wadpalliwar** [comment]
@kaumudpa Could you please try cleaning your project and then add necessary framework. Also, could you please have a look at our integration videos for reference?

**Comment by ChandraPrakashJangid** [comment]
@Mayur-Wadpalliwar I am trying to run sample app. And all available setting is already there. For reference I have added all screenshots. 
<img width="1440" alt="screen shot 2018-09-04 at 5 03 51 pm" src="https://user-images.githubusercontent.com/4987368/45028931-8f2b5500-b064-11e8-8cb3-d3a6e19ad7ba.png">
<img width="1440" alt="screen shot 2018-09-04 at 5 03 27 pm" src="https://user-images.githubusercontent.com/4987368/45028932-8f2b5500-b064-11e8-952b-7c712c847a7f.png">
<img width="1440" alt="screen shot 2018-09-04 at 5 03 20 pm" src="https://user-images.githubusercontent.com/4987368/45028933-8fc3eb80-b064-11e8-9486-cb4046501645.png">

**Comment by kaumudpa** [comment]
@Mayur-Wadpalliwar This aint working we have tried everything you have asked as well as everything according to the integration video.

**Comment by iThink32** [comment]
@kaumudpa @ChandraPrakashJangid  Our latest framework of checkout will not work on Xcode 9.2 and below , it is build with Swift 4.1 and hence you have to update your Xcode version to or above Xcode 9.3

**Comment by iThink32** [comment]
@kaumudpa @ChandraPrakashJangid  as far as the sample app is concerned , we are looking into it and will fix any issues faced.

**Comment by iThink32** [comment]
@kaumudpa @ChandraPrakashJangid check it now , this repo has the latest framework integrated and issues fixed.

**Comment by iThink32** [comment]
closing as this issue has been fixed.

**Comment by ChandraPrakashJangid** [comment]
Yes it is fixed and working perfectly now after chaining the new library.

**Comment by rmp-arasada** [comment]
@iThink32 @Mayur-Wadpalliwar I'm using latest Xcode version 10.2 and I'm still getting the same errors. please refer the screenshots.
<img width="1680" alt="Screenshot 2019-07-18 at 12 39 49 PM" src="https://user-images.githubusercontent.com/49478812/61436911-70bb0900-a959-11e9-97b1-62d03f37f87b.png">
<img width="1680" alt="Screenshot 2019-07-18 at 12 40 25 PM" src="https://user-images.githubusercontent.com/49478812/61436912-71539f80-a959-11e9-8c84-aeaedf06798d.png">
<img width="1680" alt="Screenshot 2019-07-18 at 12 41 10 PM" src="https://user-images.githubusercontent.com/49478812/61436913-71539f80-a959-11e9-991e-cadf785bf600.png">
